#!/bin/bash -e

METHOD=""
NAMESPACE=default
CONFIG_MAP=""
KEY=""

while [[ $# -gt 0 ]]; do
  case $1 in
    get)
      METHOD="get"
      shift
      ;;
    version)
      METHOD="version"
      shift
      ;;
    -n|--namespace)
      NAMESPACE="$2"
      shift # past argument
      shift # past value
      ;;    
    -k|--key)
      KEY=$2
      shift # past argument
      shift # past value
      ;;
    -c|--config|--configmap)
      CONFIG_MAP=$2
      shift # past argument
      shift # past value
      ;;
    --default)
      NAMESPACE=default
      shift # past argument
      ;;
    -*|--*)
      if [[ $NAMESPACE == default ]]; then
        NAMESPACE="${1#--*}"        
      fi      
      shift
      ;;
    *)   
      if [[ "$CONFIG_MAP" == "" ]]; then
       CONFIG_MAP="$1"
      elif [[ "$KEY" == "" ]]; then
       KEY="$1"
      fi
      shift # past argument
      ;;
  esac
done

getpods(){ 
    kubectl get deployments --namespace "$NAMESPACE" -o json | jq -r --arg CONFIG_MAP $CONFIG_MAP --arg KEY $KEY ".items | map(select(.spec.template.spec.containers[]?.env[]?.valueFrom.configMapKeyRef.name == \"$CONFIG_MAP\" and .spec.template.spec.containers[]?.env[]?.valueFrom.configMapKeyRef.key == \"$KEY\" ) |    .metadata.name) | .[]" | uniq     
 }

case $METHOD in

  "get")
    getpods
    ;;

  "version")
    echo "Version 1.0.0"
    ;;  
esac

